repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      - id: ruff
        files: "^hyperencoder/"
        types: [python]
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
        files: "^hyperencoder/"
        types: [python]
      # Run the linter.
      - id: ruff
        files: "^hyperencoder/"
        types: [python]
        args: [--fix]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.22
    hooks:
      - id: uv-lock
      - id: uv-export
        args: [--group, dev, --output-file, requirements-dev.txt]
