hydra:
  job:
    name: hyperencoder_test_${hydra:runtime.choices.model}
  job_logging:
    disable_existing_loggers: false
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
      colorlog:
        class: colorlog.ColoredFormatter
        format: '%(log_color)s[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      colorlog:
        class: colorlog.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        filename: ${hydra:runtime.output_dir}/hyperencoder.log
        formatter: simple
    root:
      handlers:
      - colorlog
      - file
      level: INFO
  run:
    dir: /data/hydra_outputs/${project_name}/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: /data/hydra_multirun/${project_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${oc.select:hydra:job.num,0}
  verbose: false
