accum_batches: 1
batch_size: 32
checkpoint_every: 1
ckpt_name: null
ckpt_path: null
dataset_config: null
devices: auto
gradient_clip_val: 0.0
learning_rate: 0.0001
log_every_n_steps: 1
logger: wandb
max_epochs: 10000000
model_config_path: null
name: vqvae_hyperencoder
num_nodes: 1
num_workers: 8
persistent_workers: false
precision: 16-mixed
pretrained_ckpt_path: null
pretransform_ckpt_path: null
project: hyperencoder
recover: false
remove_pretransform_weight_norm: false
run_id: null
save_dir: null
save_top_k: 20
seed: 42
strategy: auto
val_dataset_config: null
val_every: -1
