defaults:
- /data: default
- /model: default
- /pre_encode: default
- /hydra: default
- _self_
description: run of baseline pre encoder over dataset
project_name: audio-hyperencoder
run_name: baseline_run
seed: 42
task: pre_encode
